# Repositorios de configuración
# Uno por línea, líneas vacías y comentarios (#) ignorados

/home/ssreynoso/obsidian/obsidian-main
/home/ssreynoso/Desktop/Dev/projects/obsidian-accountability-dashboard
/home/ssreynoso/Desktop/Dev/trabajo/Aislant/aislant-framework
/home/ssreynoso/dotfiles
/home/ssreynoso/.config/nvim
/home/ssreynoso/Desktop/Dev/utils/db-queries
